### ISSUE TITLE
Detect Mismatching Binaries

### ISSUE THREAD

**Issue by tmr232** [bootleg/ret-sync#10]
This could be done in several ways. The issue that made me request this is accidentally loading a 64bit dll in IDA while debugging a 32bit application in windbg. If the plugin could verify that some basic info is matching (CPU, for instance) it could safe time on such issues.

**Comment by bootleg** [comment]
Hi tmr232, 
actually that's the purpose of the !modcheck command. It was added to the Windbg plugin to quickly check files versions (for example when the target system would have been updated and not the idb, thus failing to sync). Definitely not bullet-proof by it can help.
