### ISSUE TITLE
olly1 support

### ISSUE THREAD

**Issue by chico-depressive** [bootleg/ret-sync#15]
do you have plans for olly1 support?

can we implement our own exported versions of exported functions instead of using the .lib?

**Comment by bootleg** [comment]
Hi, 
Actually I've added support for Ollydbg 1.10 some time ago; a minimalist one though (only state sync, no command). As it wasn't really accomplished and used very seldom, I didn't commit it back then. 

See: https://github.com/bootleg/ret-sync/commit/570aa43e183c660f57ad3546920bb8bac405534f
