### ISSUE TITLE
IDA symbols sync with gdb

### ISSUE THREAD

**Issue by matrix1001** [bootleg/ret-sync#20]
If ret-sync support symbols sync , it will be really great for debugging.
Symbols include function names and some variable names(or static) are important.
https://github.com/ALSchwalm/dwarfexport  this project use ida to export dwarf for gdb.
https://github.com/danigargu/syms2elf this project export elf for gdb.
I think there is a better way to use ret-sync to do this job.
Also, pwndbg has a ida_script.py, which has a similar function to this project. But that script can resolve the symbols in IDA.
Don't know if I can do anything to help.

**Comment by bootleg** [comment]
Hi, 

been looking at this proposal recently. Totally agree that it's a good idea, awaited for many years, however I think it should be implemented as an independant tool and not part of ret-sync wich would not bring much here.

The main point for me is the lack of support from gdb for symbol handling. If I'm correct it should 
 rely on something like `add-symbol-file` command which requires complex export first to create the sym file. An api like Windbg's `IDebugSymbols3::AddSyntheticSymbol` is missing.

So mostly for me it is a won't fix here.
Thank you for the discussion.
