### ISSUE TITLE
dispatcher failed

### ISSUE THREAD

**Issue by lurumdare** [bootleg/ret-sync#22]
dispatcher failed
-> AttributeError("'NoneType' object has no attribute 'enabled'",)

**Comment by bootleg** [comment]
Hi lurumdare 

thanks for the report. Do you have any steps to reproduce the issue ?
I'm going to push an update to the IDA plugin soon and added some checks to prevent the issue some happening. However I'd like to understand the root cause to be sure it's fully patched.

Thx.
