### ISSUE TITLE
Ghidra with GDB: rln cmd not implemented

### ISSUE THREAD

**Issue by mlesin** [bootleg/ret-sync#24]
Ghidra plugin constantly says
`[<] cmd not implemented: rln`
for almost anything, like bbt command, for example.
And for rln command too, of course.

**Comment by bootleg** [comment]
Hi mlesin, 

indeed the ghidra plugin really is basic, with lots of unimplemented commands, compared to the Windbg one for example. I'll try to find time to look at it in the next weeks.

Best regards,

**Comment by bootleg** [comment]
Added many commands to the Ghidra plugin. Please see commit https://github.com/bootleg/ret-sync/commit/a76de093f8fc68400e113fd23336482576a22b4f .

Best regards,

**Comment by bootleg** [comment]
Closing the issue as inactive. Please re-open if needed.
