### ISSUE TITLE
为何总是出现这个？哪里的问题？

### ISSUE THREAD

**Issue by kouzhudong** [bootleg/ret-sync#25]
0: kd> !sync
[sync] No argument found, using default host (127.0.0.1:9100)
[sync] connect failed (check if broker is running)
[sync] probing sync
[sync] TunnelSend: tunnel is unavailable
[sync] sync aborted

**Comment by kouzhudong** [comment]
[sync] form create
Note: importing 'sip' module into <module '__main__' (built-in)>
Note: importing 'QtWidgets' module into <module '__main__' (built-in)>
[sync] default idb name: cmdguard.sys
[*] sync enabled
[*] init_broker
[*] cmdline: "C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe" -u "C:\Program Files\IDA 7.2\plugins\retsync\broker.py" --idb "cmdguard.sys"
[sync] name cmdguard.sys
[sync] module base 0x140000000
[sync] hexrays #7.2.0.181105 found
[*] broker new state: Starting
[*] broker new state: Running
[*] broker started
Shortcut F2 is used for two actions:
  @IDC:py_hotkeycb_000002913E3833F0
  hexview:EditOrApplyChanges
Shortcut for "hexview:EditOrApplyChanges" will be disabled.
Shortcut F2 is used for two actions:
  @IDC:py_hotkeycb_000002913E3833F0
  BreakpointToggle
Shortcut for "BreakpointToggle" will be disabled.
Shortcut Ctrl+F2 is used for two actions:
  @IDC:py_hotkeycb_000002913E496168
  ProcessExit
Shortcut for "ProcessExit" will be disabled.
Shortcut Ctrl+F1 is used for two actions:
  @IDC:py_hotkeycb_000002913E4961F8
  ExternalHelp
Shortcut for "ExternalHelp" will be disabled.
Shortcut Alt+F2 is used for two actions:
  @IDC:py_hotkeycb_000002913E496240
  ManualInstruction
Shortcut for "ManualInstruction" will be disabled.
Shortcut F11 is used for two actions:
  @IDC:py_hotkeycb_000002913E496318
  FullScreen
Shortcut for "FullScreen" will be disabled.
Shortcut Ctrl+F1 is used for two actions:
  @IDC:py_hotkeycb_000002913E496360
  @IDC:py_hotkeycb_000002913E4961F8
"@IDC:py_hotkeycb_000002913E4961F8" will be deleted.
[*] broker new state: Not running
[*] broker finished
[sync] idb is disabled

**Comment by bootleg** [comment]
Hi,

From what I see here, `broker.py` fails to initialize properly (possibly fail to run `dispatcher.py`). Thus without them, Windbg cannot connect to the dispatcher. IDA 7.2 thus not a compat issue I'd guess. Difficult for me to say more with these element but that's definitely where I'd start looking.

Also in rsconfig.py you can enable the option `LOG_TO_FILE_ENABLE` which may help to track the root cause. See:
https://github.com/bootleg/ret-sync/blob/b388dfcaf800d29232931a2eff49220990958eb2/ext_ida/retsync/rsconfig.py#L110

Best regards,

**Comment by kouzhudong** [comment]
i set：LOG_TO_FILE_ENABLE = True

where is log?

i can not found it.

**Comment by bootleg** [comment]
It should be generated in the `%TMP%` folder. Name pattern is  "`retsync.%s.err`".

See;
https://github.com/bootleg/ret-sync/blob/b388dfcaf800d29232931a2eff49220990958eb2/ext_ida/retsync/rsconfig.py#L123

**Comment by kouzhudong** [comment]
%TMP% 没有*retsync*err*，整个电脑都没有。

确保已经开启了：LOG_TO_FILE_ENABLE = True

**Comment by bootleg** [comment]
Ok that would mean that `err_log` is not called. There is no output from the broker so it may means it is failing very early. By chance, do you use a `.sync` config file ?

Another trick one can use to debug such issue is to pre-launch a `dispatcher.py` (from a shell with python). Then see if the broker attempts to connect to it or not.

**Comment by bootleg** [comment]
Harden conf parsing and error logging in last commit. May help, see https://github.com/bootleg/ret-sync/commit/97e93effe2fc47b63cf35df75265153d08ceec8d .

**Comment by bootleg** [comment]
Closing the issue as inactive. Please re-open if needed.
