### ISSUE TITLE
windbg kernel failed.

### ISSUE THREAD

**Issue by Pai-Po** [bootleg/ret-sync#27]
hi, i'm debugging the windows kernel. but it can't be synchronized. so i create the custom file, .sync.
```
[ALIASES]
nt=ntoskrnl.exe
```
, but once i opend ida and load the plugin, it failed. i dont' know where i made fault.Can you give me some help, thanks.
![image](https://user-images.githubusercontent.com/12437819/75093555-a2661380-55bd-11ea-8307-0785fc5ee65f.png)

**Comment by bootleg** [comment]
Hi Pai-Po, 

Thank you for reporting an issue. Are you using the last commit ? For some reason the broker dies almost instantly (it usually means it fails to create or connect to a dispatcher).

One thing you can do to collect more information is to enable the `LOG_TO_FILE_ENABLE` feature rsconfig.py, see:

https://github.com/bootleg/ret-sync/blob/347668fb5e0d53d39c8654d55ea8937e4834348a/ext_ida/retsync/rsconfig.py#L119

And set `LOG_LEVEL` to `logging.DEBUG`:

https://github.com/bootleg/ret-sync/blob/347668fb5e0d53d39c8654d55ea8937e4834348a/ext_ida/retsync/rsconfig.py#L113

Log files are generated in your `%TMP%` directory.

**Comment by Pai-Po** [comment]
I solved this issue.  The`.sync` file must have a [INTERFACE] section at least. So [ALIASES] section can't exist alone. thanks again.

**Comment by bootleg** [comment]
Thank you again for providing feedack. I'll look into it and fix that.
