### ISSUE TITLE
Make ret-sync a plugin instead of a script

### ISSUE THREAD

**Issue by tmr232** [bootleg/ret-sync#3]
That way it will be easier to use.

**Comment by bootleg** [comment]
Implemented in last commit: https://github.com/bootleg/ret-sync/commit/bf937afbae1891327690ef46ce8d88f3f00ab504

For the sake of simplicity and easier maintainability, there is no backward compatibility with IDA 6.9x branch. 

Thank you for your feedback and proposal.
