### ISSUE TITLE
Gdb bbt command: Ghidra tries to resolve wrong address

### ISSUE THREAD

**Issue by quantumbracket** [bootleg/ret-sync#31]
When gdb runs the bbt command, it sends a `[sync] rln` command to the Ghidra module which calls `rebase(rbase, raddr)` to get the final address to resolve the symbol. `rebase` then calls `imageBaseLocal.addNoWrap(raddr - rbase)`, but because gdb sets `rbase` always to 0, `raddr - rbase` is the final address already, so adding the base causes the wrong address to be returned by `rebase`.

**Comment by bootleg** [comment]
Hi quantumbracket, 

thank you for reporting this one. 

Actually, it is even worse, I fixed this issue for the `Rln` command in the commit https://github.com/bootleg/ret-sync/commit/2bd9e029a251e507024f32127555ccf81f94f94a , but missed that one in the `Bbt` command.

**Comment by bootleg** [comment]
Closing issue as inactive and fix pushed. Please re-open if needed.
