### ISSUE TITLE
How do i sync between ida and x32dbg?

### ISSUE THREAD

**Issue by yonisoft** [bootleg/ret-sync#32]
I installed the plugin for this two programs, and x32dbg says "sync is now enabled with host 127.0.0.1"
and IDA Says: "[sync] << broker << connected to dispatcher
[sync] << broker << listening on port 57776"

now how do i connected between them?

**Comment by bootleg** [comment]
Hi yonisoft, 
there shouldn't be any additional step. If nothing happen, do the two names of the program/modules you debug and the one from the idb match ?

You can see the name used by IDA in the GUI or in the log, 
`[sync] cmdline: <python.exe> <broker.py> --idb "target_name.exe"`

Btw once synced, do you also see the message below:

`[sync] set debuger dialect to x64_dbg, enabling hotkeys`

**Comment by yonisoft** [comment]
> Hi yonisoft,
> there shouldn't be any additional step. If nothing happen, do the two names of the program/modules you debug and the one from the idb match ?
> 
> You can see the name used by IDA in the GUI or in the log,
> `[sync] cmdline: <python.exe> <broker.py> --idb "target_name.exe"`
> 
> Btw once synced, do you also see the message below:
> 
> `[sync] set debuger dialect to x64_dbg, enabling hotkeys`

Hey, with the debugger, i'm debug an .exe file, but with ida i loaded a module(dll file) from the exe, does it matter?

**Comment by bootleg** [comment]
As long as you ida uses as the same name as the module (`target.dll`)you want to debug it's fine. It should get activated once you step into that module.
Could you try setting a bp into that module and once it breaks, see if sync got enabled ?

**Comment by yonisoft** [comment]
> As long as you ida uses as the same name as the module (like `target.dll` or whatever) you want to debug it's fine. It should get activated automatically once you step into that module. Before that, if you're stepping within the executable (like `target.exe`), or another module, nothing more will happen.
> 
> Could you try setting a bp into that module and once it breaks, see if sync got enabled ?

i active the sync in ida, and x64dbg, put a breakpoint on a module in x64dbg, is that same name in ida idb, the breakpoint stop on x64dbg debugger, nothing happened, what should i do?

**Comment by bootleg** [comment]
Is there some pdb information associated with your binary ? Since latest commits you should have a hint message if this is the case:

`[sync] hint: pdb name ('target_pdb.exe') differs from registered module name ('target.exe')`


To debug the issue you can enable JSON log in rsconfig.py (IDA retstync plugin) https://github.com/bootleg/ret-sync/blob/ac41c815027b2a339ad8041e6f66566962a5ed6c/ext_ida/retsync/rsconfig.py#L110

To this: 

```Python
# enable/disable logging JSON received in the IDA output window
DEBUG_JSON = True

# global log level (console output)
LOG_LEVEL = logging.DEBUG
```

When the debugger connects you should see in the log console:

```
[sync] parse_exec -> [sync]{"type":"dialect","dialect":"x64_dbg"}
[sync] set debugger dialect to x64_dbg, enabling hotkeys

```

When the idb is matched and synced with:

```
[sync] parse_exec -> [sync]{"type":"broker","subtype":"enable_idb"}
[sync] idb is enabled
[sync] parse_exec -> [sync]{"type":"loc","base":2621440,"offset":2631821}
[sync] parse_exec -> [sync]{"type":"loc","base":2621440,"offset":2631826}

```

If you can paste the logs when it fails, possibly there will be more information.

**Comment by yonisoft** [comment]
> Is there some pdb information associated with your binary ? Since latest commits you should have a hint message if this is the case:
> 
> `[sync] hint: pdb name ('target_pdb.exe') differs from registered module name ('target.exe')`
> 
> To debug the issue you can enable JSON log in rsconfig.py (IDA retstync plugin)
> 
> https://github.com/bootleg/ret-sync/blob/ac41c815027b2a339ad8041e6f66566962a5ed6c/ext_ida/retsync/rsconfig.py#L110
> 
> To this:
> 
> ```python
> # enable/disable logging JSON received in the IDA output window
> DEBUG_JSON = True
> 
> # global log level (console output)
> LOG_LEVEL = logging.DEBUG
> ```
> 
> When the debugger connects you should see in the log console:
> 
> ```
> [sync] parse_exec -> [sync]{"type":"dialect","dialect":"x64_dbg"}
> [sync] set debugger dialect to x64_dbg, enabling hotkeys
> ```
> 
> When the idb is matched and synced with:
> 
> ```
> [sync] parse_exec -> [sync]{"type":"broker","subtype":"enable_idb"}
> [sync] idb is enabled
> [sync] parse_exec -> [sync]{"type":"loc","base":2621440,"offset":2631821}
> [sync] parse_exec -> [sync]{"type":"loc","base":2621440,"offset":2631826}
> ```
> 
> If you can paste the logs when it fails, possibly there will be more information.

`[sync] sync enabled
[sync] init_broker
[sync] cmdline: "C:\Python27\python.exe" -u "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py" --idb "dllname.dll"
[sync] module base 0x10000000
[sync] hexrays not available
[sync] broker new state: Starting
[sync] broker new state: Running
[sync] broker started
[sync] parse_exec -> [sync]{"type":"broker","subtype":"msg","msg":"connected to dispatcher"}
[sync] << broker << connected to dispatcher
[sync] parse_exec -> [sync]{"type":"broker","subtype":"notice","port":"60857"}
[sync] << broker << listening on port 60857`

i don't have pdb of my binary, and its seems like it doesn't print fails in the logs only waiting for connection, maybe i'm doing something wrong?

**Comment by bootleg** [comment]
I'm worried why  that it seems the IDA plugin doesn't receive the "dialect" message from the dispatcher (set to unknown by default before a debuggers connects). It may indicate that the dispatcher fails to initialize. 

Do their Python processes appear in you processes list ?

You can enable extra debugging for dispatcher and broker in the ` rsconfig.py` file:

```Python
# enable/disable broker and dipatcher exception logging to file
LOG_TO_FILE_ENABLE = True
```
If it crash they should write log file in `%TMP%` folder.

**Comment by yonisoft** [comment]
> I'm worried why that it seems the IDA plugin doesn't receive the "dialect" message from the dispatcher (set to unknown by default before a debuggers connects).
> 
> ```
> [sync] << broker << listening on port 57950
> [sync] parse_exec -> [sync]{"type":"dialect","dialect":"unknown"}  <== this one
> ```
> 
> It may indicate that the dispatcher fails to initialize properly. Do their Python processes appear in you processes list ?
> 
> You can enable extra debugging for dispatcher and broker in the ` rsconfig.py` file:
> 
> ```python
> # enable/disable broker and dipatcher exception logging to file
> LOG_TO_FILE_ENABLE = True
> ```
> 
> If it crash they should write log file in `%TMP%` folder.

`Caching 'Functions window'... ok
[sync] form create
[sync] default idb name: client_panorama.dll
[sync] sync enabled
[sync] init_broker
[sync] cmdline: "C:\Python27\python.exe" -u "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py" --idb "client_panorama.dll"
[sync] module base 0x10000000
[sync] hexrays not available
[sync] broker new state: Starting
[sync] broker new state: Running
[sync] broker started
[sync] plugin loaded
[sync] parse_exec -> [sync]{"type":"broker","subtype":"msg","msg":"connected to dispatcher"}
[sync] << broker << connected to dispatcher
[sync] parse_exec -> [sync]{"type":"broker","subtype":"notice","port":"51706"}
[sync] << broker << listening on port 51706`

still the same, i don't even get "parse_exec" line.

**Comment by bootleg** [comment]
So you have no file (following the pattern "retsync.%s.err") in your tmp folder ?

Are the two extra Python processes present under IDA Pro process tree (one running `broker.py`, the other one `dispatcher.py`).

From x64dbg you use entry from menu / "!sync" in command line ?

 If it is possible for you, it may help to test replacing x64dbg by windbg just to troubleshot what happens.

**Comment by yonisoft** [comment]
> So you have no file (following the pattern "retsync.%s.err") in your tmp folder ?
> 
> Are the two extra Python processes present under IDA Pro process tree (one running `broker.py`, the other one `dispatcher.py`).
> 
> From x64dbg you use entry from menu / "!sync" in command line ?
> 
> If it is possible for you, it may help to test replacing x64dbg by windbg just to troubleshot what happens.

i prefer to not replace x32dbg, and the retsync log:

`2020-03-19 15:54:57,388 [DEBUG] server.loop error
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 302, in <module>
    server.loop()
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 240, in loop
    self.handle(s)
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 225, in handle
    self.parse_exec(s, req)
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 207, in parse_exec
    req_handler(s, hash)
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 182, in req_kill
    self.notice_dispatcher('kill')
  File "C:\Program Files\IDA Pro 7.4\plugins\retsync\broker.py", line 97, in notice_dispatcher
    self.notify_socket.sendall(rs_encode(notice))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10053] An established connection was aborted by the software in your host machine
`

**Comment by bootleg** [comment]
Ok this is interesting, this is from "`retsync.broker.err`", is there a "`retsync.dispatcher.err`" as well ?

Is `python.exe` allowed to open a listening port on your network ? Do you use a custom configuration ".sync" file (with possitly a specific ip) ?

The last line:
`[Errno 10053] An established connection was aborted by the software in your host machine`

seems to indicate that the broker fails while waiting for input from the dispatcher.

**Comment by yonisoft** [comment]
> Ok this is interesting, this is from "`retsync.broker.err`", is there a "`retsync.dispatcher.err`" as well ?
> 
> Is `python.exe` allowed to open a listening port on your network ? Do you use a custom configuration ".sync" file (with possitly a specific ip) ?
> 
> The last line:
> `[Errno 10053] An established connection was aborted by the software in your host machine`
> 
> seems to indicate that the broker fails while waiting for input from the dispatcher.

i don't have dispatcher.err, yea its opening in my firewall python.exe

**Comment by bootleg** [comment]
I've been thinking about it this weekend and I don't understand what could happen here.

Do you have any log from the sync plugin in `x64dbg` log tab ?

Just a oneshort try with Windbg could help troubleshot this possibly.

**Comment by yonisoft** [comment]
> I've been thinking about it this weekend and I don't understand what could happen here.
> 
> Do you have any log from the sync plugin in `x64dbg` log tab ?
> 
> Just a one short try with Windbg could help troubleshot this possibly.

I Don't have windbg, i tried to install it but its complicated, i don't have logs for x64dbg, nothing, only "start sync", if you want i can give you TeamViewer, just send me your discord or another way that we can communicate

**Comment by bootleg** [comment]
Log tab is right there in x64dbg:

![log](https://user-images.githubusercontent.com/1045805/77427139-276b6500-6dd6-11ea-8c3d-3b9d4d3b173e.png)

**Comment by yonisoft** [comment]
> Log tab is right there in x64dbg:
> 
> ![log](https://user-images.githubusercontent.com/1045805/77427139-276b6500-6dd6-11ea-8c3d-3b9d4d3b173e.png)

haha, yea i mean, i have same logs as you have.

**Comment by bootleg** [comment]
My bad for the log.
Just added the !idblist command to x64dbg, not related but it may help getting more information from the situation. You need to sync first !sync then you can call !idblist

**Comment by yonisoft** [comment]
> My bad for the log.
> Just added the !idblist command to x64dbg, not related but it may help getting more information from the situation. You need to sync first !sync then you can call !idblist
> 
> See commit [fa1171f](https://github.com/bootleg/ret-sync/commit/fa1171feee533cc40fd36838ef7da8416de5c476)
> 
> The pre-built binary is available on the Azure pipeline.

[sync] not synced, !idblist command unavailable

**Comment by bootleg** [comment]
Would it be possible that another program already listens on the port 9100 (like a zombie python process running an instance of the dispatcher)  ? The dispatcher socket is currently created with `socket.SO_REUSEADDR` flag thus it would go un-noticed.  Connection would success but message never reach the broker which seems consistent with what you describe.

Also you can try to run the dispatcher manually.

`python dispatcher.py`

Btw to debug the reuse issue, you can switch from `socket.SO_REUSEADDR` to  socket.SO_EXCLUSIVEADDRUSE.

When I do so and run` !sync` then `!idblist`  I get the reply!

```
[sync] sync command!
[sync] probing connection
[sync] sync is now enabled with host 127.0.0.1
[sync] idblist command!
> currently connected idb(s):
    no idb client yet
```

**Comment by bootleg** [comment]
Ok so from the logs above, the `!sync` command was succesful, dispatcher informed the idb about the your debuger. Dispatcher has one idb register. To me it looks good, if you break info the module "dllname.dll" and it has the same name in the process as in the idb, it should enable the idb.

**Comment by bootleg** [comment]
Closing the issue as I believe it is fixed.  Please reopen if necessary.
