### ISSUE TITLE
Rebase exception sync IDA/WinDBG

### ISSUE THREAD

**Issue by danigargu** [bootleg/ret-sync#34]
Hi! 

I just tested your amazing plugin and I get this exception after setting a breakpoint in IDA.

It seems like `self.base_remote` is None.

```
Exception in ida_kernwin.UI_Hooks dispatcher function: SWIG director method error. Error detected when calling 'UI_Hooks.preprocess_action'
Traceback (most recent call last):
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins/SyncPlugin.py", line 922, in preprocess_action
    self.hooked[action_name]()
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins/SyncPlugin.py", line 629, in bp_notice
    offset = self.rebase_remote(ea)
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins/SyncPlugin.py", line 174, in rebase_remote
    offset = (offset - self.base) + self.base_remote
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

WinDBG Log:
```
0: kd> .load sync
[sync] DebugExtensionInitialize, ExtensionApis loaded
0: kd> !sync
[sync] No argument found, using default host (127.0.0.1:9100)
[sync] sync success, sock 0x258
[sync] probing sync
[sync] sync is now enabled with host 127.0.0.1
0: kd> !idblist
> currently connected idb(s):
    [0] XXXX.sys
0: kd> !idbn 0
> current idb set to 0
```

When I try to configure a manual bp (in WinDBG) on the module and then run `!sync`, I get the following error:

```
0: kd> !sync
[sync] sync update
[sync] failed to GetModuleByOffset for offset: 0xfffff8022bf31538
```

Now I have mapped the module manually and now it seems to sync fine.

```
1: kd> !modmap 0xfffff8022bf30000 0x8000 XXXX.sys
*** WARNING: Unable to verify timestamp for XXXX.sys
```

Would it be possible to fix it?

**EDIT**: After several attemps, multiple debug restarts, etc, the plugin constantly fails, sometimes preventing setting breakpoints (exception above), and at other times memory addresses do not match IDA / Windbg (maybe wrong rebase). Now, even `modmap` doesn't work (AddSyntheticModule failed).

Thanks!

**Comment by bootleg** [comment]
Hi danigargu, 

The issue you're describing reminds me some of the discussion we had in https://github.com/bootleg/ret-sync/issues/28 (especially the `GetModuleByOffset ` failure).

If it is a legitimately loaded driver, it should not happen. I don't know how Windbg handles internally its context, but something you could try before syncing is to use Windbg's `.reload` to make sure Windbg's internal context is up to date (I don't have the options in mind but I believe `.reload` without option it will only reload kernel symbols).

You should not have to use `!modmap` exept for very specific use case like _manually_ loaded code/payload.

The bp issue may be a side effect of the Windbg extension failure to update its state.

**Comment by danigargu** [comment]
Hi @bootleg ! Thanks for your quick response!
I just revised the SyncPlugin.py file and I thing think I know what the problem is.

The `base_remote` is only setted when a rebase is requested:
https://github.com/bootleg/ret-sync/blob/master/ext_ida/SyncPlugin.py#L160

So, in my case it seems that it is never established and therefore the exception above.

I'm reversing a driver, but without symbols, so I would be interested in being able to establish the first breakpoint from IDA, but since there has never been a rebase (loc req), the plugin does not know the remote base.

I just tried an "ugly" solution and it works for me to establish a correct remote base:

```python
def rebase_remote(self, offset):
    if self.base_remote is None:
        self.base_remote = idaapi.ask_addr(0, "Remote module base is not yet resolved. Use this one:")
```

Would it be possible to fix it in a better way?

It would be nice if the address of the remote base was sent from WinDBG, after "sync", and not in the first req_loc rebase, since if you are debugging in the context of another module, the remote base will be invalid (as it was happening to me).

**Comment by bootleg** [comment]
Hi, 

You're right about `base_remote`, the thing is you should not have been able to send a bp command if your idb was not "enabled" (meaning that debugger has reached this module and at least a sync has been sent and the dispatcher matched you're idb name).

https://github.com/bootleg/ret-sync/blob/556afb14afb819ca48154067c7b493ac0e63c089/ext_ida/SyncPlugin.py#L621

As a general rule, I tried to keep the code base as simple as possible and to avoid context sharing between the debugger and IDA as much as possible (debugger can crash, restart or many other events), but I understand the limitation here. Manual solution like you did may be a solution, or requesting module base address from the debugger itself through a command. 

Btw, did the `.reload` command helped ?

**Comment by danigargu** [comment]
Hi @bootleg ,

Before I was already doing `.reload` to update the info, although the error I mentioned at the beginning of GetModuleByOffset was due to that :)

The `self.is_active` looks like I'm forcing it by doing `idbn 0` from WinDBG, right?

I would like to be able to set the first BP in IDA, and without correct remote_base it is not possible.

I wish I could help you fix this limitation. How could I request the module base address from the debugger through a command? Is there currently functionality for that?

Thanks!!

**Comment by danigargu** [comment]
I just created a new command in `ext_windbg` called `set_rbase`, which receives the module name from IDA, resolves its base address and forwards it back to IDA. 

I don't know which is the most appropriate place to put this sync it in SyncPlugin.py. So far I have left it in the 'enable_idb' block and it works nice for me: https://github.com/bootleg/ret-sync/blob/556afb14afb819ca48154067c7b493ac0e63c089/ext_ida/SyncPlugin.py#L547

if you want, I do pull-request so you can check it

**Comment by bootleg** [comment]
Hi danigargu, 

Actually `idbn 0` is also a feature that we should not have to use in the nominal use case.

I need to think about it  more through-fully. Right now the built-in logic is that when a debugger sends a message, dispatcher blindly forward it to the active idb. In the scenario we discuss, the idb is inactive. There may be many idb connected to the dispatcher at the same time.
There are solution, I just want to make sure I'm not breaking logic and/or other plugins behavior.

**Comment by danigargu** [comment]
Hi bootleg,

I understand you, better not break anything:)
My steps to make it clearer:

* [windbg] Kernel attach (without previous breakpoints). I dont have the driver symbols, so i would like to be able to set the first breakpoints from IDA (but IDA doesn't know the remote base) 
```
.load sync
!sync
!idbn 0
```
* [ida] If I set a breakpoint, it can't because it doesn't know the remote base.
* [windbg] If I perform any step, the dispatcher sends a message to the IDA, with the current offset + module base (for example: ntoskrnl or other), and therefore IDA establishes a wrong remote base.

I think you understood me. If you manage to support this scenario it would be perfect!

Thanks!!

**Comment by bootleg** [comment]
Yes, thank you for the extra input. A smooth solution may be to buf-up the `idbn` command. And make it sends the base address of the module/idb that is request. I'll test that asap to see if it is convenient.

**Comment by bootleg** [comment]
Ok just pushed some ideas. Please see `!idb`, `!idbn`, `!idblist`, `!modlist`.

I reused existing logic and command, thus only adding a very basic `!rbase` command on the disassembler side. Will make it easier to port to Ghidra as well.

The part that may be confusing is how Windbg refers to module: module name, image name, loaded image name (with codeview info). Module name may have whitespace replaced with underscores.

**Comment by danigargu** [comment]
Hi bootleg,

I just tried it and it works perfect!
The only problem I found is that the `idb` command displays the address with 32 bits format string.

```
0: kd> !idb xx
> mod: "xx"
> base address: 0x70350000
```

The correct address is `0xfffff80070350000`. But the sync works correctly :)

Thanks!

**Comment by bootleg** [comment]
My bad, fixed.
