### ISSUE TITLE
Labeling and comments x64dbg/Ghidra

### ISSUE THREAD

**Issue by Rourke101** [bootleg/ret-sync#35]
I have installed everything and got sync'ed. I can step over and both programs are coordinated.

However I am wondering how I can populate labels/comments/var names from Ghidra to x64dbg and viceversa:
1- I opened a file with some changes made from Ghidra but these are not populated into x64dbg. 
2- After synchronizing, by setting the comment manually in either program (e.g. by using ";") does not do any synchronization and the comment remains local to the program.
3- If I try to manually execute "cmt Test", "cmt -a 401039 Test", "cmt "Test"", etc from x64dbg I get an error saying "Not enough arguments! At least 2 arguments must be specified"

1 is the most convenient, as I might have a disassembled file with some renaming already and it would be great to have this populated into the debugger.

2 is also nice, as I can make changes as they are both opened, by using the usual options from Ghidra or x64dbg, and get it populated to the other.

3 is not ideal, since I need to use specific commands (instead of e.g. pressing ";" for comment) and it seems to work only while they both are open.

**Comment by bootleg** [comment]
Hi Rourke101, 

I understand what you're looking for and it reminds me of issue https://github.com/bootleg/ret-sync/issues/20 as well.

Regarding porting labels/comments/var names from Ghidra to x64dbg, you may want to look at x64dbgida (https://github.com/x64dbg/x64dbgida) and port it to Ghidra. I believe x64dbg has features like `dbsave`/`dbload `which may help.

As for issue https://github.com/bootleg/ret-sync/issues/20 I think this is largely out of scope for ret-sync. Syncing tools interactions in real-time (comment/rename/symbols, etc.) is definitely a road I don't want to take. Too much complexity hooking stuff for small benefice. I my own view, the disassembler (IDA/Ghidra) is the cold storage while the debugger is _volatile_, that why most of the commands take data from debugger and push it to the disassembler.

Btw, in last commit (https://github.com/bootleg/ret-sync/commit/bec5834ec1daf90ac54d541921ab7872016883b3) I've added command `!cmt` `!rcmt` and `!synchelp` which may bring a very partial answer to your needs.

 "`cmt Test`", "`cmt -a 401039 Test`", "`cmt "Test`" <= you're interacting with x64dbg commands, not ret-sync ones (would be prefixed with `!`).
https://help.x64dbg.com/en/latest/commands/user-database/commentset.html

**Comment by Rourke101** [comment]
Thank you for your answer!

I suppose I got just the previous built where !cmt and !synchelp were not available.

Just one more question, not sure if I should open another issue - How can I move the pointer in x64dbg to the code I am looking at in Ghidra?  So I am looking at an instruction in Ghidra and I would like to move my cursor in x64dbg to that instruction (not moving EIP, just the view). At the moment I have to copy the bytes from Ghidra and look for them manually in x64dbg, but having synchronization I guess there is a faster way.

**Comment by bootleg** [comment]
> I suppose I got just the previous built where !cmt and !synchelp were not available.

I just added them based on your feedbacks :)

> Just one more question, not sure if I should open another issue - How can I move the pointer in x64dbg to the code I am looking at in Ghidra? So I am looking at an instruction in Ghidra and I would like to move my cursor in x64dbg to that instruction (not moving EIP, just the view). At the moment I have to copy the bytes from Ghidra and look for them manually in x64dbg, but having synchronization I guess there is a faster way.

Well that would be relatively easy I guess, just sending x64dbg the `disasm ` command with a rebased address. It would consume another shortcut though.

> I'm not sure this is an existing feature but it would be great to have it. Same to the ability to set BPs from Ghidra/IDA (I think this is available in Windbg but I can't find the way to do it for x64dbg).

This feature is already implemented in ret-sync, one you idb is enable (the debugger is in the module matching your idb/ghidra, if you set a bp in your disassembler it'll be sent to the debugger (look for F2 / ctrl-F2 shortcuts).

**Comment by Rourke101** [comment]
Yes, a `disasm` with the rebased address will work great.

> This feature is already implemented in ret-sync, one you idb is enable (the debugger is in the module matching your idb/ghidra, if you set a bp in your disassembler it'll be sent to the debugger (look for F2 / ctrl-F2 shortcuts).

Mmmm... Ghidra can't set BPs as far as I know (it doesn't have a debugger yet). That's why I thought more of a ret-sync option where one can send the command "I want a BP here".

**Comment by Rourke101** [comment]
By the way, the other commands are:

```
entry("hbp", "xxx ") -->  bph 00007FF73FB6917E, x, 1
entry("bp1", "xxx ") -->  bp 00007FF73FB6917A, ss
entry("hbp1", "xxx ") --> I have been investigating and I'm not sure this can be done with a single 
                          command. But I know it can be done with two commands:
                          bph 00007FF73FB6917E, x, 1
                          SetHardwareBreakpointSingleshoot 00007FF73FB691AE
                          (or, to avoid confusion: SetHardwareBreakpointSingleshoot 00007FF73FB691AE, 1)
```

I'm not doing the changes myself as I'm not sure how they will work with the "," parameters after the address. But I am happy to test them if you release the changes.

**Comment by bootleg** [comment]
Thank you for the PR. Just merged, I'll update the plugin binary release soon. I'll add the `!rbase` command at the same time.

> It would be great if !cmt set the comment in x64dbg too,

This seems straightforward to do. I'll look into it.

`Probably it wouldn't hurt to add a potential parameter to the cmt`

Funny, I asked myself this as well. I added the optional switch when developing the Windbg extension but it turned out that I've almost never used it. That's why I choose to squeeze it for the x64dbg extension.


> If the command is run more than once the comments are appended.

Yes, actually it is on purpose. My thoughts were that I prefer to have no surprise and not remove any user's information without explicit request (like `!rcmt`).

**Comment by bootleg** [comment]
I implemented the `disasm` jump through the `translate ` command (`alt-f2` from Ghidra/IDA). This behaviour is a bit different than what is implemented in the Windbg extension however I feel it is ok as  x64dbg is far less command-line oriented than Windbg I guess.

**Comment by bootleg** [comment]
Closing the issue as I believe it is fixed. Please reopen if necessary.
