### ISSUE TITLE
"rrln" command ignores remote base when returning addresses from symbols

### ISSUE THREAD

**Issue by Gbps** [bootleg/ret-sync#38]
https://github.com/bootleg/ret-sync/blob/3590c72a9603f768431d47da63e808aaaafa99c7/ext_ida/SyncPlugin.py#L385

```python
    # return address for a given idb's symbol
    def req_rrln(self, hash):
        sym, rbase, offset, base = hash['sym'], hash['rbase'], hash['offset'], hash['base']

        rs_log("%s -  0x%x - 0x%x - 0x%x" % (sym, rbase, offset, base))

        addr = idc.get_name_ea_simple(str(sym))
        if addr:
            self.notice_broker("cmd", "\"cmd\":\"%s\"" % addr)
            rs_log("resolved address: %s" % addr)
        else:
            rs_log("could not resolve address for symbol %s" % sym)
```

This function ignores the base argument from `hash['base']` and does not calculate an address based off of the ida base and remote base.

I believe this should change so that the ida base is remove from the address and the remote base is added before returning. This should result in an address that is relative to the remote module.

```python
    # return address for a given idb's symbol
    def req_rrln(self, hash):
        sym, rbase, offset, base = hash['sym'], hash['rbase'], hash['offset'], hash['base']

        rs_log("%s -  0x%x - 0x%x - 0x%x" % (sym, rbase, offset, base))

        addr = idc.get_name_ea_simple(str(sym))
        if addr:
            # rebase the address to remote base
            addr = addr - self.base + hash['base']
            self.notice_broker("cmd", "\"cmd\":\"%s\"" % addr)
            rs_log("resolved address: %s" % addr)
        else:
            rs_log("could not resolve address for symbol %s" % sym)
```

**Comment by bootleg** [comment]
Hi Gbps, 

Thank you for reporting the two issue.  I fxed them in the last commits https://github.com/bootleg/ret-sync/commit/792af4895af0f9fe56e6ae2056417ef981ea03d8 (for IDA including the Py2/3 issue).

Actually if I still understand what we were trying to achieve here. There is no need for base/rbase/offset. We just want to resolve a symbol locally and return a rebased address. If we're talking to the idb it means it is enable and has received its remote base address so we can use the available `rebase_remote` function.

**Comment by Gbps** [comment]
Hey there, thanks for the quick fix. I agree it can also just use the rebased information saved locally from the enabled idb. The fixes look good from my end!
