### ISSUE TITLE
GDB plugin is Python 3 only

### ISSUE THREAD

**Issue by mpalmer** [bootleg/ret-sync#40]
Just tried to use ret-sync on a GDB installation that only had Python 2.7 support.  Bombed with complaints about line 524:

```
super().__init(sync, True)
TypeError: super() takes at least 1 argument (0 given)
```

I have extremely minimal Python fu, but some Googling suggests that the syntax being used there is Python 3-specific.  Using the copy of `sync.py` from [this commit](https://github.com/bootleg/ret-sync/commit/a76de093f8fc68400e113fd23336482576a22b4f) (which is the commit before [the one that introduced that new syntax](https://github.com/bootleg/ret-sync/commit/2bd9e029a251e507024f32127555ccf81f94f94a)) loads fine (I'm yet to use it in anger).

I'm not asking for Python 2.7 support to necessarily be retained -- it is well past its use-by date.  It's just that the README still says that Python 2 is supported, and if the intention is that that is no longer the case, it'd be good to get the docs up-to-date.

**Comment by bootleg** [comment]
Hi @mpalmer, 

indeed, I try to preserve Python 2/3 compat as much as possible. I'll see to update the README. Could you tell me which version of GDB you're using

I do not have a py2/GDB readily available to test now; however, would the fix below do the trick for the p2/p3 GDB compat ?

```
if sys.version_info[0] == 2:
  from builtins import super
```

**Comment by mpalmer** [comment]
I'm using the gdb from MinGW, which is 7.5.  I don't think it's GDB version specific, though, so much as Python version specific.

I can confirm that adding the Python snippet you quoted does allow the script to load into GDB successfully, although I also had to `pip install future` to make it work -- otherwise it just complains that there's no module named `builtins`.  Given that it's not trivial to infer that you need to install `future` to get `builtins`, it might be worth catching the `ImportError` and giving a friendly error message explaining the need to `pip install future`.

**Comment by bootleg** [comment]
Thank you for your feedback, fix pushed. Please close if it is ok.

**Comment by mpalmer** [comment]
The fix isn't quite right.  Despite the package being named `future`, the module you need to import from is called `builtins` (I don't understand it either).  So it needs to be `from builtins import super`, rather than `from future import super`.

**Comment by bootleg** [comment]
Rhaa fuck me; pushed the wrong syntax. Udated.

For future reference, saving test case below.

```
import sys

if sys.version_info[0] == 2:
    try:
        from future.builtins import super
    except ImportError as e:
        print("[xxxx] 'future' package is needed (e.g., 'pip install future')")
        raise(e)

class Bli(object):

    def __init__(self):
        print("Bli")

    def pouet(self):
        print("pouet")

class Bla(Bli):

    def __init__(self):
        super().__init__()
        print("Bla")

b = Bla()
b.pouet()
```

**Comment by bootleg** [comment]
Closing the issue as I believe it is fixed.  I may revert to using old class style to remove the extra requirement of future though. Please reopen if necessary.
