### ISSUE TITLE
Can this directly set breakpoints in lldb/gdb?

### ISSUE THREAD

**Issue by dvcrn** [bootleg/ret-sync#43]
I wasn't completely sure because all the breakpoint commands mention **over windebug** which doesn't exist on mac. 

From my short test with IDA, setting breakpoints in IDA doesn't reflect inside lldb so I'm guessing no, but might also just be my setup that's the problem.

**Comment by bootleg** [comment]
Setting breakpoints from the disassembler (IDA/Ghidra) is supported for GDB but not for LLDB. I'm not familliar with the API, it may be possible without too much efforts, I'll look into it when I have time.

**Comment by dvcrn** [comment]
If you give me some pointers on where you do it in gdb I could try to take a look 👍

**Comment by bootleg** [comment]
Nothing complex. Basically one needs the ability to poll the socket safely for incoming commands like:https://github.com/bootleg/ret-sync/blob/f12d8631a41d34bffb211fb458a161e1fc818634/ext_gdb/sync.py#L299

Then I guess using something like the core of the `cmd ` command will do the trick.

```
    ci = sc._dbg.GetCommandInterpreter()
    res = lldb.SBCommandReturnObject()

    ci.HandleCommand(command, res)
    if res.Succeeded():
        out = res.GetOutput()
        if not out:
            return
        out = base64.b64encode(out)
        pinfo = sc.procinfo()
        if not pinfo:
            return
```

**Comment by bootleg** [comment]
Please see https://github.com/bootleg/ret-sync/commit/422cac01baa7d8421e862d0593fe6ef8627a2ad2

**Comment by bootleg** [comment]
I'm closing this one as it is implemented now. Please re-open if needed.
