### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by kaisar149** [bootleg/ret-sync#46]
I've been looking around but still haven't found how to connect ret-sync with windbg + ghidra.

After pressing 'start listening' it shows N/A on the debugger option and on the last one.
Will you please help me on setting it up?

**Comment by bootleg** [comment]
Hi @kaisar149  o/

in Ghidra:

1.  `alt+s` (to start listening), status should switch to `listening`

Windbg:

1. `.load sync`
2. `!sync`

If connection is successful, `Client debugger` will display windgb info.

**Comment by kaisar149** [comment]
Thanks
