### ISSUE TITLE
Unable to locate input point  TitanGetProcessInformation()

### ISSUE THREAD

**Issue by junknet** [bootleg/ret-sync#47]
Maybe the author changed the API name?

**Comment by bootleg** [comment]
Hi @junknet, 

indeed, it seems related to a change in x64dbg (GleeBug). A related issue is open here https://github.com/x64dbg/x64dbg/issues/2450

I'll look into it to understand how to fix that.

Best regards,

**Comment by bootleg** [comment]
Follow-up, as far as I understand it, Gleedbg debug engine implements a wrapper that emulates TitanEngine. A couple of API are missing, breaking some plugins as this one. However, it look like fixes are in the pipe, see this commit for example:

https://github.com/x64dbg/GleeBug/pull/48/commits/ad67ff50fcc43043f6e1986f23eb0375d04ed6e5

Possibly the best solution is to move to the bridge api and not to rely on lower level TitanEngine.

**Comment by bootleg** [comment]
Commit https://github.com/bootleg/ret-sync/commit/83c91470435cef7681fd13392ec69ac1b93602aa should have fixed the issue.
Please let me know if it is ok for you.
