### ISSUE TITLE
Any luck on MacOs?

### ISSUE THREAD

**Issue by snaiperskaya96** [bootleg/ret-sync#48]
Hi, thanks a lot for your work on ret-sync.
I've been trying to get a decent reverse engineering setup running on mac but so far with no luck.
I've tried using ret-sync on ghidra with gdb and lldb, with the former seemingly connecting and syncing up but hanging if you  set a breakpoint using F2 (and anyway always showing "Client program: none") while the latter not being recognized and ignoring bps and all (`dialect: unknown` `client debugger: unknown`).
Is anyone using ret-sync on macos successfully?

**Comment by bootleg** [comment]
Hi @snaiperskaya96 

As for issue https://github.com/bootleg/ret-sync/issues/43 and https://github.com/bootleg/ret-sync/issues/42 I'd like to bring the same features to lldb (reverse commands) and intend to do so in the upcoming weeks/months.

I am not aware of someone around me using ret-sync on MacOS.

Regarding gdb, that bothers me. Could you check that Ghidra is actually listening on the port 9100 when ret-sync is running ? In https://github.com/bootleg/ret-sync/issues/44 there was also an issue with the port which should not have happened.

**Comment by bootleg** [comment]
Please see https://github.com/bootleg/ret-sync/commit/422cac01baa7d8421e862d0593fe6ef8627a2ad2

**Comment by bootleg** [comment]
I'm closing this one as it is implemented now. Please re-open if needed.
