### ISSUE TITLE
Is there minimum version of gdb?

### ISSUE THREAD

**Issue by dannyatftecu** [bootleg/ret-sync#49]
I just cloned and got ret-sync added to Ghidra OK.

I am also running gdb 7.9.1 and when I type in source sync.py, I get:

sync.py:1: Error in sourced command file:

(I am on Windows 10, with python 2.7.6.)  Is there min. GDB version I should be running?  Or is the script only good on UNIX boxes?

**Comment by bootleg** [comment]
Hi @dannyatftecu, 

Not really, as long as the gdb Python API is available which should be ok for most of even middy up-to-date systems.

Something I can think of to based on the error you get, is to make sure the gdb package you have is a "full" one, not a gdb-minimal-like (which doesn't embed the Python API):

e.g. for Debian packages:

Package: gdb-minimal (8.2.1-2 and others)   NOK
https://packages.debian.org/buster/gdb-minimal

Package: gdb (8.2.1-2 and others)  OK
https://packages.debian.org/buster/gdb


You can easily test by sourcing `bla.py`, with a single line in the file: `print("bla")`

If you got the same error, then most probably the Python API is not available in your package.

**Comment by dannyatftecu** [comment]
Well, it seems that Python package is in there since it does print '$1 = "bla"' when I 'source bla.py'.

Any other suggestion to try?

**Comment by bootleg** [comment]
That's weird, trying the same thing locally would just output "bla" and nothing more. Also the error you got, the first line is just comment.

Can I ask you what release/package of gdb you are using (you said you're on Windows right?) ?

**Comment by bootleg** [comment]
Closing this one as it has been open and inactive for a month. Please reopen if necessary.
