### ISSUE TITLE
Add option to disable breakpoints

### ISSUE THREAD

**Issue by tmr232** [bootleg/ret-sync#5]
Currently, the plugin can create windbg breakpoints directly from IDA (using `F2`), but there is not way to disable them via IDA.

Also, the created BP does not show up in the IDA GUI, making it difficult to keep track.

**Comment by bootleg** [comment]
Hi, 
indeed that's an issue I've think about already without getting a satisfying solution. Here is why.
Looking at ret-sync design, at first, it's the debugger that is meant to control IDA's gui. "Inverted" controls were added later.

I often debug vm and kernel code, crashing or rebooting the OS abruptly more often than not, thus making it complex to track the debugger state (maintain a breakpoints list, knowing when they're still active, etc.). Besides, an most importantly IDA is not meant to replace the debugger controls (like a bl command). 

Thus, again, I choose not to bring unnecessary complexity to the plugin's code for a small gain in usability. To be honest I was even thinking about removing less useful function like the bpcmds wrapper.

**Comment by tmr232** [comment]
Well, as soon as I have time I'll see if I can figure a workable solution and suggest it.

Regarding the `bpcmds`, noticed that only after posting this issue. It seems like a great command, but I couldn't get it to work. Seems like the sync messages got split in two and caused parsing errors. I'll be submitting a relevant issue soon.
