### ISSUE TITLE
No communication between Ghidra and gdb

### ISSUE THREAD

**Issue by lachyc** [bootleg/ret-sync#51]
ret-sync never seems to sync with gdb. Screenshot is attached showing ret-sync loaded in both gdb and Ghidra and Ghidra listening on port 9100 but no connection made. I can confirm the java process listed in `lsof` is Ghidra.

![image](https://user-images.githubusercontent.com/18381424/97515253-c992a180-19e4-11eb-946d-daf0a9bccb47.png)

**Comment by bootleg** [comment]
Hi @lachyc 

sorry for the stupid question, do you send a "`sync`" command in gdb after sourcing the plugin (I don't see it in the gdb shell in bottom right) ?

Once loaded, the plugin does not automatically sync with the target disassembler. When I need to do that each time gdb is starting I usually use a command file (that source then sync) with `-x` switch as startup.

**Comment by lachyc** [comment]
Sorry, I misinterpreted the readme! I can now sync gdb and Ghidra.
