### ISSUE TITLE
Can't determine the current process's PID

### ISSUE THREAD

**Issue by ktinkone** [bootleg/ret-sync#53]
I have add a .sync file in my .idb directoty. When i start retsync plugin ,it also find this .sync file.But when i enter cmd 'sync' in gdb,it prints  "Python Exception <class 'gdb.error'> Can't determine the current process's PID: you must name one.: ".

gdb 
![image](https://user-images.githubusercontent.com/63765593/98337865-3d1b5b00-2044-11eb-8a69-7c337d5248a3.png)

ida pro  output window
![image](https://user-images.githubusercontent.com/63765593/98337965-62a86480-2044-11eb-860e-9cc5fa6220c5.png)

.sync file
![image](https://user-images.githubusercontent.com/63765593/98338022-76ec6180-2044-11eb-92f4-08ebd466ac5b.png)

**Comment by bootleg** [comment]
Hi @ktinkone , 

The issue here is simple. gdb did not find your configuration file. The disassembler and debuggers plugins are independent, possibly running on different hosts. So basically you need two config files.
The general idea is that the debugger config is global while the disassembler config is local (attached to an idb first for example). Back to gdb it look for a config file in these locations:

```
# location searched by the debugger for a configuration file
CONFIG_LOCATIONS = [
    os.path.abspath(os.path.dirname(__file__)),
    os.environ['HOME']]
```

When found, you'll get an output in the shell, eg. :

```
[sync] configuration file loaded from: /home/user/.sync
       interface: 192.168.112.1:9100
[sync] initialization context:
{
    "pid": 123456,
    "mappings": [
        [
            93824992231424,
            93824994467840,
            2236416,
            "ls"
        ]
    ]
}

[sync] init
[sync] 18 commands added
```

best regards

**Comment by ktinkone** [comment]
Thank you very much. I have solved the question。
(^v^)       (^v^)
But i get a new problem.I guess you may know about it.

question :  unknown module at current PC: 0xdc7e2820

![image](https://user-images.githubusercontent.com/63765593/98512479-553be600-22a1-11eb-90bf-27e6c88cdf74.png)

i think this may  due to that ida pro don not load .so file . I have try a lots of ways. but i don't solve it . I want to know if this problem cause  by  it.  thanks !!!

**Comment by ktinkone** [comment]
Thank you  . I have solved the question. ^v^  ^v^ 
Best   regards.

**Comment by bootleg** [comment]
Hi great, 

I was about to say that 0xdc7e2820 in not in the range you defined [0x8048000, 0xB74AE20]. It may be another module.

If it is ok for you, can we close the issue ?

**Comment by ktinkone** [comment]
Yes，you are right . I did encounter this problem. 
I  have solve the problem by set a breakpoint at 0x0804EA00  which  is shown as the entry address  by the IDA PRO .
It is ok for me now .
We can close the issus.
Thanks again for this  great plugin.
^v^
