### ISSUE TITLE
Can I use this with a custom gdb stub?

### ISSUE THREAD

**Issue by VelocityRa** [bootleg/ret-sync#54]
Most emulators like [RPCS3](https://github.com/rpcs3/rpcs3) and [pcsx2](https://github.com/PCSX2/pcsx2) feature gdb stubs ([example](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/GDB.cpp)) that allow a gdb client like gdb's or IDA's to debug the emulated guest.

I would like to have an emulator as the "debugger" & sync that with Ghidra. 

Can it work with arbitrary gdb stubs this way? Or are the existing GDB tools only for using it with a program that's run/managed by GDB?

If not, I suppose I'd need to write and extension myself, like the one for `x64dbg` etc. (but presumably in the emulator's own codebase). Any docs/pointers on that or should I just study the existing one's code to figure it out?

Thank you, great plugins!

**Comment by bootleg** [comment]
Hi @VelocityRa 

Can I ask what would be you use case ? To debug/single step program running within the emulator ?

If I understand correctly. My first bet would be to keep GDB in the picture. And not redevelop to much feature (like to debugging logic, program's state UI/display, etc.)

For example one can run:

`gdbserver :2345 /bin/ls > /dev/null 2>&1`

then within gdb:

`gdb$ target remote :2345`

and from there use ret-sync plugin transparently to sync with a Ghidra/IDA program.

Thus I guess if you use gdb to connect to the emulators' stubs that would do the job and you'd be able to follow the traced code in your favorite disassembler. That would be something like: `IDA/Ghidra <-> gdb <-> emulator`.

**Comment by VelocityRa** [comment]
Thanks, I'll try it at some point (RPCS3's gdbstub is currently broken) and re-open if there are issues.
