### ISSUE TITLE
Ghidra 9.2 compatibility

### ISSUE THREAD

**Issue by LoZio** [bootleg/ret-sync#56]
Is there an ETA for Ghidra 9.2 compatibility now that it is released to the public?
You can update the properties file to be seen as valid, but the configuration phase crashes.
Thanks

**Comment by bootleg** [comment]
Hi @LoZio, 

please see commit  https://github.com/bootleg/ret-sync/commit/a13e0ddcb797f74619f39fda279fae7946bf881c.

Rebuilt the plugin for the last release of Ghidra. Seems to work ok although I didn't check the changelog extensively.

**Comment by bootleg** [comment]
Note for self: need to update decompiler highlight 

https://github.com/NationalSecurityAgency/ghidra/pull/784

https://github.com/NationalSecurityAgency/ghidra/blob/8f1be0932ac035c3da550f2bcd9ddefbc5918362/Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/component/DecompilerHighlightService.java

**Comment by LoZio** [comment]
The install from zip phase went fine, but I didn't have the "configure extension" popup on first launch and there are no buttons on the bar.

**Comment by bootleg** [comment]
I've observed that when an extension crash once, it is removed from the tool.
You can check from the Code browser window menu: `File -> Configure -> Experimental`, make sure retsync is ticked.

![experimental - Copy](https://user-images.githubusercontent.com/1045805/99230485-ac850d80-27ef-11eb-9770-ea703029e15d.png)

**Comment by LoZio** [comment]
Something does not compute
![image](https://user-images.githubusercontent.com/869890/99231362-cffc8800-27f0-11eb-9ad2-721a95c48f78.png)
and
![image](https://user-images.githubusercontent.com/869890/99231417-e1459480-27f0-11eb-9abd-9156eac6da32.png)

**Comment by LoZio** [comment]
Ok, something breaks somewhere. If you delete the ghidra profile and restart the process with the 9.2 package it works.
It even works better than befere, it does not ask for any first-run config.

**Comment by bootleg** [comment]
Just to be sure. Did you use the menu from the Code Browser (the disassembler) window ? Not the one from the Ghidra launcher / project manager (I see a red icon in your screenshots).

I'm always confused with these menus.

**Comment by LoZio** [comment]
I used the menus from the Ghidra launcher, thet is what I did on 9.1.
The important part here is avoiding to install the old 9.1 plugin as it corrupts something in the profile. The 9.2 package works fine using the launcher menus to install.

**Comment by bootleg** [comment]
Ok good. If there is no other issue, can we close this one ?


Note: Decompiler highlight updated for Ghidra 9.2 in https://github.com/bootleg/ret-sync/commit/2f833b059183e6b469cfb8338d545939aada4a6f.

**Comment by LoZio** [comment]
Yes

**Comment by bootleg** [comment]
Great. Thank you for all the feedback!
