### ISSUE TITLE
IDA Pro 7.5 and Ghida

### ISSUE THREAD

**Issue by Ponchet** [bootleg/ret-sync#58]
Today I decided to use the Python debug to find out what was going on with this fantastic software.
There is an error when is loading the API (idaapi), IDA has changed the name of dll and how it is making the connection with function, Do you pretend to rewrite the program?

**Comment by bootleg** [comment]
Hi @Ponchet 

could you paste the console output (exception log) from IDA? I don't get what's the issue so far.

Best regards.

**Comment by Ponchet** [comment]
Dear,
below the information from IDA

Loading file 'F:\Temp\IDA\AsProjet.exe' into database...
Detected file format: Portable executable for AMD64 (PE)
Loading processor module C:\Program Files (x86)\IDA Pro 7.5 SP2\procs\pc64.dll for metapc...Initializing processor module metapc...OK
Autoanalysis subsystem has been initialized.
C:\Users\Dell Rugged\AppData\Roaming\Hex-Rays\IDA Pro\plugins\idaapi.py: invalid syntax (C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/idaapi.py, line 4)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/idaapi.py", line 4
    ${IMPORTS}
    ^
SyntaxError: invalid syntax

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\idaxml.py: Missing parentheses in call to 'print'. Did you mean print(msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/idaxml.py, line 2625)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/idaxml.py", line 2625
    print msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?

[sync] [-] failed to import Qt libs from PyQt5
(<class 'ImportError'>, ImportError('DLL load failed while importing sip: The specified module could not be found.'), <traceback object at 0x000001D57B249F00>)
C:\Users\Dell Rugged\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SyncPlugin.py: DLL load failed while importing sip: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/SyncPlugin.py", line 54, in <module>
    from PyQt5 import QtCore, QtWidgets
ImportError: DLL load failed while importing sip: The specified module could not be found.

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\xml_exporter.py: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_exporter.py, line 60)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_exporter.py", line 60
    print "\n" + msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)?

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\xml_importer.py: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_importer.py, line 56)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_importer.py", line 56
    print "\n" + msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)?

  0. Creating a new segment  (0000000140001000-0000000140244000) ... ... OK
  1. Creating a new segment  (0000000140244000-0000000140342000) ... ... OK
  2. Creating a new segment  (0000000140342000-0000000140362000) ... ... OK
  3. Creating a new segment  (0000000140362000-0000000140394000) ... ... OK
Reading imports directory...
Reading exception directory (.pdata)...
Parsing .pdata and creating 16826 functions...
  4. Creating a new segment  (0000000140248400-0000000140342000) ... ... OK
File C:\Windows\system32\ws2_32.dll is used for module WS2_32...
Plan  FLIRT signature: Microsoft VisualC v14 64bit runtime
Plan  FLIRT signature: Microsoft VisualC 64bit universal runtime
Plan  FLIRT signature: MFC 7-14 64bit
main() function at 1401DBAE0, named "WinMain"
Assuming __fastcall calling convention by default
Type library 'mssdk64_win7' loaded. Applying types...
Types applied to 268 names.
Marking typical code sequences...
Flushing buffers, please wait...ok
File 'F:\Temp\IDA\AsProjet.exe' has been successfully loaded into the database.
Hex-Rays Decompiler plugin has been loaded (v7.5.0.200728)
  License: 55-2FD4-F731-D2 P.Y.G Team, Personal license (1 user)
  The hotkeys are F5: decompile, Ctrl-F5: decompile all.
  Please check the Edit/Plugins menu for more informaton.
IDAPython Hex-Rays bindings initialized.
C:\Users\Dell Rugged\AppData\Roaming\Hex-Rays\IDA Pro\plugins\idaapi.py: invalid syntax (C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/idaapi.py, line 4)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/idaapi.py", line 4
    ${IMPORTS}
    ^
SyntaxError: invalid syntax

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\idaxml.py: Missing parentheses in call to 'print'. Did you mean print(msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/idaxml.py, line 2625)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/idaxml.py", line 2625
    print msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?

[sync] [-] failed to import Qt libs from PyQt5
(<class 'ImportError'>, ImportError('DLL load failed while importing sip: The specified module could not be found.'), <traceback object at 0x000001D57B1AFE00>)
C:\Users\Dell Rugged\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SyncPlugin.py: DLL load failed while importing sip: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/Dell Rugged/AppData/Roaming/Hex-Rays/IDA Pro/plugins/SyncPlugin.py", line 54, in <module>
    from PyQt5 import QtCore, QtWidgets
ImportError: DLL load failed while importing sip: The specified module could not be found.

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\xml_exporter.py: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_exporter.py, line 60)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_exporter.py", line 60
    print "\n" + msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)?

C:\Program Files (x86)\IDA Pro 7.5 SP2\plugins\xml_importer.py: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)? (C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_importer.py, line 56)
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA Pro 7.5 SP2\python\3\ida_idaapi.py", line 614, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), script, 'exec')
  File "C:/Program Files (x86)/IDA Pro 7.5 SP2/plugins/xml_importer.py", line 56
    print "\n" + msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n" + msg)?

IDA is analysing the input file...
You may start to explore the input file right now.
---------------------------------------------------------------------------------------------
Python 3.10.0a3 (tags/v3.10.0a3:8bae2a9, Dec  7 2020, 20:13:25) [MSC v.1927 64 bit (AMD64)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>

Happy New year with health and peace for you and your family.

Conectado 30-Dec-20 9:51:52 PM, bootleg <notifications@github.com> escreveu:
Hi @Ponchet [https://github.com/Ponchet]
could you paste the console output (exception log) from IDA? I don't get what's the issue so far.
Best regards.

**Comment by bootleg** [comment]
Hi, 

it looks like it is not an issue with ret-sync but with the Ghidra to IDA exporter plugin (`idaxml.py` and `xml_importer.py`). You are running Py3 while the scripts have been developped for Py2.

**Comment by Ponchet** [comment]
wow, Really?
thanks a lot!

Marinaldo Lira Ponchet
SysGraphic Comércio e Serviços.
Tel.: 55-21-3026-1913 / 2612-1089
Fax.: 55-21-2612-1089
Cel.: 55-21-98622-7339
marinaldo@sysgraphic.com.br [mailto:marinaldo@sysgraphic.com.br]
sysgraphic@gmail.com [mailto:sysgraphic@gmail.com]
marinaldo.ponchet@gmail.com [mailto:marinaldo.ponchet@gmail.com]
www.sysgraphic.com.br [http://www.sysgraphic.com.br/]
Conectado 03-Jan-21 1:28:47 PM, bootleg <notifications@github.com> escreveu:
Hi,
it looks like it is not an issue with ret-sync but with the Ghidra to IDA exporter plugin (idaxml.py and xml_importer.py). You are running Py3 while the scripts have been developped for Py2.

**Comment by bootleg** [comment]
Closing this one as it seems ok. Please re-open if necessary.

**Comment by Ponchet** [comment]
Thanks a lot!

Marinaldo Lira Ponchet
SysGraphic Comércio e Serviços.
Tel.: 55-21-3026-1913 / 2612-1089
Fax.: 55-21-2612-1089
Cel.: 55-21-98622-7339
marinaldo@sysgraphic.com.br [mailto:marinaldo@sysgraphic.com.br]
sysgraphic@gmail.com [mailto:sysgraphic@gmail.com]
marinaldo.ponchet@gmail.com [mailto:marinaldo.ponchet@gmail.com]
www.sysgraphic.com.br [http://www.sysgraphic.com.br/]
Conectado 11-Jan-21 8:03:37 PM, bootleg <notifications@github.com> escreveu:
Closing this one as it seems ok. Please re-open if necessary.
