### ISSUE TITLE
IDA7.5，ERROR:[sync] idb is disabled

### ISSUE THREAD

**Issue by Azha0** [bootleg/ret-sync#59]
Ret-sync is a very useful tool, and I've used it before.But when I used it again recently, it didn't work.Please give me a hand
IDA7.5 cannot be used,Did I make a configuration mistake?
Output infomations:
[sync] default idb name: PEhash.exe
[sync] sync enabled
[sync] cmdline: "C:\python39-x64\python.exe" -u "D:\01_Tools\06_IDA7.5\IDA_7.5\plugins\retsync\broker.py" --idb "PEhash.exe"
[sync] module base 0x400000
[sync] hexrays #7.5.0.201028 found
[sync] broker started
[sync] plugin loaded
[sync] << broker << connected to dispatcher
[sync] << broker << beacon not received (possible dispatcher error)
[sync] << broker << received kill notice
[sync] broker finished
[sync] idb is disabled

**Comment by bootleg** [comment]
Hi @Azha0 

in rsconfig.py, could you please enable `LOG_TO_FILE_ENABLE `. As in:

`LOG_TO_FILE_ENABLE = True`

Looks like the dispatcher is dying or fail to properly initialize for some reason.

**Comment by Azha0** [comment]
Thank you so much for your assistance.
But when I set LOG_TO_FILE_ENABLE  = True and LOG_LEVEL = logging.DEBUG, The log file has nothing.
Now, I suspect there is something wrong with my computer!

IDA Output info:
[sync] restarting broker
[sync] sync enabled
[sync] init_broker
[sync] cmdline: "C:\python39-x64\python.exe" -u "D:\01_Tools\06_IDA7.5\IDA_7.5\plugins\retsync\broker.py" --idb "PEhash.exe"
[sync] module base 0x400000
[sync] hexrays #7.5.0.201028 found
[sync] broker new state: Starting
[sync] broker new state: Running
[sync] broker started
[sync] << broker << connected to dispatcher
[sync] << broker << binding on port 58528
[sync] << broker << beacon not received (possible dispatcher error)
[sync] << broker << received kill notice
[sync] broker new state: Not running
[sync]     check tmp file retsync.<broker|dispatcher>.err if you think this is an error
[sync] broker finished
[sync] idb is disabled

**Comment by bootleg** [comment]
Could you try to run the dispatcher manually please. From a console:

`D:\01_Tools\06_IDA7.5\IDA_7.5\plugins\retsync>python dispatcher.py`

**Comment by Azha0** [comment]
When I run dispatcher.py, I find the problem.
The port 9100 is being used by my G Hub update.
**Thank you very much for your help**. RET-SYNC is great.

**Comment by bootleg** [comment]
Thanks for the nice feedback!

I'll improve the error message. Actually I added in the dispatcher code to check if the port is available or not 
https://github.com/bootleg/ret-sync/blob/a35293db9b0f9844dcf7454877e4d8acbda5b2db/ext_ida/retsync/dispatcher.py#L99

This is checked with the beaconing exchange. 

You got:
`[sync] << broker << beacon not received (possible dispatcher error)`

Instead
`[sync] << broker << beacon not received (possible dispatcher error, please ensure that port XXX is available)`

Would have given the information/hind you need.

**Comment by bootleg** [comment]
I'm closing this one as I think it is now covered. Please reopen if necessary.

Thank you!
