### ISSUE TITLE
Feature: set break in ghidra decompiled view/listing then break in x64dbg

### ISSUE THREAD

**Issue by mprevot** [bootleg/ret-sync#60]
Would it be possible, doable, simple, to add an "add break point" feature where on add a break point in ghidra/s decompiled view or listing and then have the break added in x64dbg/some debugger ?

**Comment by bootleg** [comment]
Hi @mprevot, 

not sure if I get the question correctly but it is already implemented (for most debuggers), see https://github.com/bootleg/ret-sync#ghidra-usage , for example the F2 shortcut.

Is that what you're looking for?

**Comment by mprevot** [comment]
@bootleg Indeed this is what I'm looking for. However the f2 or ctrl+f2 break (from ghidra) **do not add breakpoint** in x64dbg. Sync is correct from x64dbg to ghidra (breaks). Using master from less than 1 week and x64dbg from 8 jan 2021.

**Comment by bootleg** [comment]
Got it. I'll look into it and see if I can reproduce.

**Comment by mprevot** [comment]
Yes the debugger is synced:

[sync] attempting to connect to 127.0.0.1:9100
[sync] sync success, sock 0x1334
[sync] probing connection
[sync] sync is now enabled with host 127.0.0.1

no "Breakpoint at 00XXXXX set!" when F2 from ghidra

**Comment by bootleg** [comment]
Nope, My bad, I tested with IDA. Looks like F* hotkeys are broken in Ghidra.

**Comment by mprevot** [comment]
I'm using Ghidra 9.2.1 public, 20202-dec-15 1409 and Java 15.0.1.

**Comment by bootleg** [comment]
I'am not fully sure about that. If the callbacks were called for example for the bp hotkey, it should at least print log something like 

```
[>] ret-sync-bp
    local addr: 00402792, remote: 0xaf2792
```

in Ghidra's console. In widget other than "Listing" nothing happens. (and at the same time Alt-S/ Alt-Shift-S are working fine)

**Comment by mprevot** [comment]
I was using release build of ret-sync; with debug I have 

```
ret-sync-bp
    local addr: 18002cd12, remote: 0x7ffff519cd12
```

the break appears in x64dbg when I ask a bp from listing.
However, from the widget `decompile` it does not work, and with release of ret-sync it never works.

**Comment by bootleg** [comment]
Thanks for the feedback. Right now I'm a bit clueless about what may happened here.

The issue looks very similar to this one: https://github.com/NationalSecurityAgency/ghidra/issues/2641

**Comment by mprevot** [comment]
I downloaded the sources 2020 january 15th, and built ret-sync {release,debug}x{32 bits,64 bits} with VS2019, using the latest c/c++ toolset v142.

I'll update to ghidra 9.2.3 when it is released. I'm updating to 9.2.2.

**Comment by bootleg** [comment]
Ho that's right, I had the Ghidra extension in mind and didn't get what was the debug version.

Regarding the x64dbg  that's weird, release and debug are almost similar.

**Comment by bootleg** [comment]
Checked gain with Ghidra 7.2.3; still got the issue with hotkeys in graph/decomp view. Don't have more clues right now.

**Comment by bootleg** [comment]
Based on a quick test, it looks like Ghidra 10.0 BETA fixed the issue. Please see: https://github.com/bootleg/ret-sync/commit/3a9edb2e74ade7549a8369ec047ea4acae794db2

**Comment by bootleg** [comment]
Closing this one as I believe the issue is solved. Please reopen if necessary.
