### ISSUE TITLE
breakpoints do not set in IDA

### ISSUE THREAD

**Issue by 0xdeadc0d3** [bootleg/ret-sync#62]
I get a `[sync] >> set bp 0x4016a5` message, the breakpoint is set in x32dbg but not in ida.

**Comment by 0xdeadc0d3** [comment]
There is also bug with export breakpoints (CTRL+F1)
IDA log: `[sync] bp 0: bp helloworld+0x16b9`
`[sync] export done`

x32dbg log: `Invalid addr: "helloworld+0x16b9"`

**Comment by bootleg** [comment]
Hi @0xdeadc0d3 

First, regarding "breakpoints do not set in IDA". Indeed, this feature is like a deported way to set a bp in the debugger, the plugin doesn't keep track of the bp in the disassemblers (ie. setting a bp is not reflected in the disassembler). 


For the second issue.
`x32dbg log: Invalid addr: "helloworld+0x16b9"`

Indeed, I first added this feature to take advantage of the ".bpcmds" command from Windbg. Other debuggers have been added later and I didn't extend the support for them in that command. I'll look into it. It seems not so complex to rebase the address before sending the commands.

**Comment by bootleg** [comment]
Just pushed a fix for the error:
`_x32dbg log: Invalid addr: "helloworld+0x16b9_"`

Please see: https://github.com/bootleg/ret-sync/commit/3f79b4d73796602cfee959dd5cd3358fdeb0a2a1

**Comment by 0xdeadc0d3** [comment]
> Just pushed a fix for the error:
Yes, it is works. Thank you

> First, regarding "_breakpoints do not set in IDA_". Indeed, this feature is like a deported way to set a bp in the debugger, the plugin doesn't keep track of the bp in the disassemblers (ie. setting a bp is not reflected in the disassembler).

I made sync for breakpoints IDA -> x64dbg but i don't know how do sync for x64dbg -> IDA so if it is possible it would be great if you made that one. If it is impossible just close the issue.

**Comment by bootleg** [comment]
Hi @0xdeadc0d3

I haven't found a simple way to  x64dbg -> IDA and more generally I'd like to avoid starting hooking into the debuggers engine. I'll close the issue for now, but if I found a way to do it properly I'll implement the feature.

thank you for your feedback.
