### ISSUE TITLE
Ghidra - program unavailable

### ISSUE THREAD

**Issue by Rev3rsedC0re** [bootleg/ret-sync#65]
I used ret-sync to sync ghidra with gdb. 
Everything goes right until I try running the program in gdb, then it runs correctly on gdb but ghidra doesn't show anything.
The console says:
[*] retsync init
[>] ret-sync enable
[>] server listening 
[>] server started
[<] new_dbg: dbg connect - Linux #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64
             dialect: gdb
[x] program unavailable: program_name

Is there a way to fix this?

**Comment by Rev3rsedC0re** [comment]
Doesn't matter, I found a solution just after I had posted the issue :)

**Comment by luizhtss** [comment]
Hello, how did you fix it?
