### ISSUE TITLE
AttributeError: 'module' object has no attribute 'new_thread'

### ISSUE THREAD

**Issue by sn0ot** [bootleg/ret-sync#66]
Running GDB in a chroot and recieving the following error[ regarding events in Python](https://sourceware.org/gdb/current/onlinedocs/gdb/Events-In-Python.html)

```
(gdb) source sync.py
[sync] configuration file loaded from: /root/.sync
       interface: 192.168.1.56:9234
[sync] init
Traceback (most recent call last):
  File "sync.py", line 1070, in <module>
    SYNC_PLUGIN = Sync(rs_cfg, rs_commands)
  File "sync.py", line 390, in __init__
    gdb.events.new_thread.connect(self.newthread_handler)
AttributeError: 'module' object has no attribute 'new_thread'
```

ret-sync's `sync.py` DOES work if not running in a chroot.

```
(gdb) source sync.py
[sync] configuration file loaded from: /root/.sync
       interface: 192.168.1.56:9234
[sync] init
[sync] 18 commands added
```
 I suspect this issue stems from GDB but `sync.py` fails too early for me to debug what is actually happening. Any ideas?

**Comment by bootleg** [comment]
Hi @sn0ot 

this is a hard one. Just incase make sure that the gdb package inside the chroot is gdb full not the gdb-minimal package. However it may have crashed sooner.

Which version of gdb are you running ? I found a similar error message in this mailing list: https://sourceware.org/pipermail/gdb-prs/2017q3.txt

**Comment by bootleg** [comment]
Hopefully this issue is fixed by default thanks to the commit above (https://github.com/bootleg/ret-sync/commit/98698a5705dac4e5ffe834002017a7a339eeb2bc)

Please re-open if necessary. Thank you for reporting the issue.
