### ISSUE TITLE
Color Configuration

### ISSUE THREAD

**Issue by tmr232** [bootleg/ret-sync#7]
At the moment, it is unclear how one should customize colors. 

Having a separate configuration file for colors (and other configuration?) will be much appreciated.

**Comment by williballenthin** [comment]
color config is something thats handled differently in so many plugins. some of the plugins i maintain suffer from this, too. if a few of us agree on a consistent mechanism, i'd be happy to support it from my side.

this project is not necessarily (but might be) the appropriate place to discuss this.

**Comment by williballenthin** [comment]
using `QSettings` may be a good idea, since that's what its built for. though, potentially harder to distribute/share color schemes. i've used the following routines for configuring various aspects of IDA scripts:

```
def prompt_for_string(title, label):
    class MyForm(idaapi.Form):
        def __init__(self):
            self.invert = False
            idaapi.Form.__init__(self, r"""STARTITEM
<#%s#%s:{iStringInput}>
""" % (title, label), { 'iStringInput': idaapi.Form.StringInput(), })

        def OnFormChange(self, fid):
            return 1

    f = MyForm()
    f.Compile()
    f.iStringInput.value = ""
    ok = f.Execute()
    val = f.iStringInput.value
    f.Free()
    return val, ok
    

class PromptingSettings(QtCore.QSettings):

    def value(self, key, defaultValue=None):
        """
        Override QSettings to prompt user for initial config value
          if it doesn't yet exist.
        """
        if not self.contains(key):
            if defaultValue is not None:
                return defaultValue

            # import QtGui on demand to satisfy server installations?
            logger = logging.getLogger("PromptingSettings")
            # wanted to use QtGui.QInputDialog.getText(), but it locks up IDA when not in plugin mode
            val, ok = prompt_for_string("",
                                        "Please enter the initial configuration value for %s. "
                                        "Refer to the plugin installation guide for suggested values." % (key))
            if not ok:
                logger.warning("No initial value provided for: %s", key)
            else:
                logger.debug("Setting initial value for %s to: %s", key, val)
                self.setValue(key, val)
        return super(PromptingSettings, self).value(key, defaultValue=defaultValue)
```

and then you can do:

```
config = PromptingSettings("bootleg", "ret-sync")
bg_color = config.value("ret-sync.colors.bg")
```

if the config has not been initialized, it prompts the user for an initial value.

**Comment by tmr232** [comment]
@williballenthin Now that you bring it up, it seems like a good idea to create some convention (backed up with relevant C and Python modules) for storing IDA plugin configurations. Having to configure each plugin separately (in `.my-plugin-name` files of different formats) is not much fun.

But we should probably move this discussion elsewhere - https://gist.github.com/tmr232/d1f4d31e174d2cbcca19

**Comment by williballenthin** [comment]
good idea, I'll contribute there

**Comment by bootleg** [comment]
Global configuration, extracted to rsconfig.py as suggested. Thank you for the discussion and ideas.

See commit https://github.com/bootleg/ret-sync/commit/bf937afbae1891327690ef46ce8d88f3f00ab504
