### ISSUE TITLE
Update to Ghidra 10?

### ISSUE THREAD

**Issue by Rourke101** [bootleg/ret-sync#70]
When is it normally updated?
I can't see v9.2.4 either

**Comment by bootleg** [comment]
ret-sync is normally updated when I notice the Ghidra's update, which is not an exact science.

Please see: https://github.com/bootleg/ret-sync/commit/ad141fff3fffe1649ccbb7e1b199c00a87b123bc and https://github.com/bootleg/ret-sync/commit/3a9edb2e74ade7549a8369ec047ea4acae794db2

**Comment by Rourke101** [comment]
Great! Thanks
