### ISSUE TITLE
networok connect question

### ISSUE THREAD

**Issue by Byzero512** [bootleg/ret-sync#73]
Hi.
the situation is that ida in local machine can connect to debugger in remote machine，but debugger in remote machine can not connect to local machine.
how can ret-sync work for it?

**Comment by bootleg** [comment]
Hi @Byzero512 

IDA plugin creates a server (the dispatcher) listening on port 9100. It must be reachable by the debugger. There is a need for a kind of shared interface.  In the situation of remote debuging with VM, I've used Host-Only interface for example. Would using SSH port forwarding be a possibility?

Best regards,
bootleg.

**Comment by Byzero512** [comment]
oh, thanks for reply, the port forwarding is possible.
