### ISSUE TITLE
breakpoints not syncing Ghidra --> WinDbg

### ISSUE THREAD

**Issue by gigawatts** [bootleg/ret-sync#79]
Ghidra v10.0.3
WinDbg Preview (Windows 10)

When using F2 to send a breakpoint to WinDbg from Ghidra, it displays a message in the Scripting Console:
`[>] ret-sync-bp`
But a breakpoint never gets sent to WinDbg UNLESS WinDbg is already paused at a previously set WinDbg breakpoint, then F2 adds new breakpoints just fine after that. I'm not sure if that is by design or not, but it means it is required to set a breakpoint first in WinDbg (like $exentry), then add additional breakpoints from Ghidra. Yes confirmed the RetSyncPlugin status was connected in both scenarios.

Also, there is currently no binary release available in the `ext_windbg` dir, though I was able to compile the sln provided.

**Comment by bootleg** [comment]
Great if it works for you as well.

If there is no more issue, can we close this one ?

**Comment by gigawatts** [comment]
good to close, thank you
