### ISSUE TITLE
create release for BN plugin manager support

### ISSUE THREAD

**Issue by psifertex** [bootleg/ret-sync#86]
Good news! Binary Ninja now supports subfolders for plugins so it will grab the whole repository and use a subfolder as the BN plugin to make installation automatic via the plugin manager.

The only thing you need to do is [tag a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and I can get it added to the plugin manager which should make the plugin even more discoverable for Binary Ninja users. 

Once you've made an initial release just let me know by closing this issue and I will add it to the plugin manager. Future updates are semi-automatic (just require me to manually review/push) and you don't have to do anything other than do another release.

**Comment by bootleg** [comment]
Hi @psifertex 

please find https://github.com/bootleg/ret-sync/releases/tag/ext_bn_community_release_v0.1.0
