### ISSUE TITLE
Exception TypeError on IDA Plugin

### ISSUE THREAD

**Issue by luoshuijs** [bootleg/ret-sync#87]
```python
D:\IDA_Pro_v7.5\plugins\SyncPlugin.py: unsupported operand type(s) for +: 'set' and 'tuple'
Traceback (most recent call last):
  File "D:\IDA_Pro_v7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "D:/IDA_Pro_v7.5/plugins/SyncPlugin.py", line 63, in <module>
    PYTHON_PATH = rsconfig.get_python_interpreter()
  File "D:/IDA_Pro_v7.5/plugins\retsync\rsconfig.py", line 224, in get_python_interpreter
    PYTHON_PATHS = PYTHON_PATHS + localpaths
TypeError: unsupported operand type(s) for +: 'set' and 'tuple'
```
https://github.com/bootleg/ret-sync/blob/900eba44922b1ed4507470dda2084bc4a179ced8/ext_ida/retsync/rsconfig.py#L224

This is because `PYTHON_PATHS` is a set and `localpaths` is a tuple, and these two variable types do not support addition.

I commented out this line of code and after adding the following code the plugin was loaded successfully.

```python
for localpath in localpaths:
              PYTHON_PATHS.add(localpath)
```

**Comment by bootleg** [comment]
Hello @luoshuijs ; 

it should be fixed in the commit above, see https://github.com/bootleg/ret-sync/commit/ffb9fae4b076688492554d81582f8244307211f0

Thanks a lot for reporting it. 

Just let me know if it is ok to close the issue.

**Comment by luoshuijs** [comment]
Thanks for your reply and fix, I'm closing this issue.
