### ISSUE TITLE
Can't get windbg and Ghidra 10.1.2 to sync

### ISSUE THREAD

**Issue by TheIronWolfModding** [bootleg/ret-sync#90]
Hello, I am facing some silly problem.  In Ghidra, ret-sync prints the following on startup:

programOpened: BLAH

But when I break in windbg, I get:

[x] program unavailable: blah.exe

Seems like ret-sync fails to associate BLAH and blah.exe, any hints?

Note that my BLAH project is rebased to 0x0000, maybe that's part of an issue?  Thanks!

**Comment by bootleg** [comment]
Hi @TheIronWolfModding , 

for whatever reason it seems the program name associate with this binary in your Ghidra project is `BLAH` without the extension. Even if the name matching is **not** case sensitive it won't match the name with the extension. Image base is not an issue.

From project windows, you can right click on your program then "`About Program`" and see "`Program Name`".

As a workaround you can use the "`ALIAS`" option from a .sync configuration file.

**Comment by TheIronWolfModding** [comment]
Thanks a lot for getting back to me, I got it to work! :)

This is simply amazing haha, it works wonderful! :)
